"""add virtual clock offset for admin time-travel

Revision ID: 11e5dd940811
Revises: 7819fbc78056
Create Date: 2026-08-21 18:46:59.470149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e5dd940811'
down_revision: Union[str, None] = '7819fbc78056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('time_offset_seconds', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('leagues', 'time_offset_seconds', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'time_offset_seconds')
    # ### end Alembic commands ###
