"""add tactic, training, sponsors, matches

Revision ID: 17f4f9ca1112
Revises: aa96e046c846
Create Date: 2026-08-18 09:20:03.633768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f4f9ca1112'
down_revision: Union[str, None] = 'aa96e046c846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'teams',
        sa.Column(
            'tactic',
            sa.Enum('BALANCED', 'PASS_HEAVY', 'RUN_HEAVY', 'BLITZ', 'PREVENT', name='tactic'),
            nullable=False,
            server_default='BALANCED',
        ),
    )
    op.alter_column('teams', 'tactic', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'tactic')
    # ### end Alembic commands ###
