"""add match play_events

Revision ID: 1a6c057ee97f
Revises: ce5b2f328c9e
Create Date: 2026-09-19 18:52:29.107076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6c057ee97f'
down_revision: Union[str, None] = 'ce5b2f328c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('play_events', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'play_events')
    # ### end Alembic commands ###
