"""add bot-controlled teams

Revision ID: 30c4c412bdda
Revises: 64cd6881bf7f
Create Date: 2026-08-20 16:25:47.696858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c4c412bdda'
down_revision: Union[str, None] = '64cd6881bf7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('is_bot', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('teams', 'is_bot', server_default=None)
    op.add_column('users', sa.Column('is_bot', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('users', 'is_bot', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_bot')
    op.drop_column('teams', 'is_bot')
    # ### end Alembic commands ###
