"""league flow, timed upgrades, sponsors rework, roster transfers, trades

Revision ID: 64cd6881bf7f
Revises: cfad572230c2
Create Date: 2026-08-20 15:54:26.239732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64cd6881bf7f'
down_revision: Union[str, None] = 'cfad572230c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadium_upgrades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('target_level', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stadium_upgrades_team_id'), 'stadium_upgrades', ['team_id'], unique=False)
    op.create_table('trade_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_team_id', sa.Integer(), nullable=False),
    sa.Column('to_team_id', sa.Integer(), nullable=False),
    sa.Column('target_player_id', sa.Integer(), nullable=False),
    sa.Column('offered_player_id', sa.Integer(), nullable=True),
    sa.Column('cash_offer', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='trade_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['offered_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['target_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_offers_from_team_id'), 'trade_offers', ['from_team_id'], unique=False)
    op.create_index(op.f('ix_trade_offers_to_team_id'), 'trade_offers', ['to_team_id'], unique=False)
    op.add_column('players', sa.Column('listed_for_transfer', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('players', 'listed_for_transfer', server_default=None)
    op.add_column('players', sa.Column('asking_price', sa.Integer(), nullable=True))

    # Existing sponsor contracts predate the day-based template system and have no
    # sensible mapping onto it -- start fresh rather than inventing dummy values.
    op.execute("DELETE FROM sponsors")
    op.add_column('sponsors', sa.Column('template_key', sa.String(length=30), nullable=False))
    op.add_column('sponsors', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('sponsors', sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('sponsors', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('sponsors', 'created_at')
    op.drop_column('sponsors', 'matches_remaining')

    op.add_column('users', sa.Column('display_name', sa.String(length=50), nullable=True))
    op.execute("UPDATE users SET display_name = split_part(email, '@', 1) WHERE display_name IS NULL")
    op.alter_column('users', 'display_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    op.add_column('sponsors', sa.Column('matches_remaining', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sponsors', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('sponsors', 'expires_at')
    op.drop_column('sponsors', 'signed_at')
    op.drop_column('sponsors', 'name')
    op.drop_column('sponsors', 'template_key')
    op.drop_column('players', 'asking_price')
    op.drop_column('players', 'listed_for_transfer')
    op.drop_index(op.f('ix_trade_offers_to_team_id'), table_name='trade_offers')
    op.drop_index(op.f('ix_trade_offers_from_team_id'), table_name='trade_offers')
    op.drop_table('trade_offers')
    op.drop_index(op.f('ix_stadium_upgrades_team_id'), table_name='stadium_upgrades')
    op.drop_table('stadium_upgrades')
    # ### end Alembic commands ###
