"""add season/playoff engine fields

Revision ID: 7819fbc78056
Revises: 9db914ed237a
Create Date: 2026-08-21 18:24:21.969793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7819fbc78056'
down_revision: Union[str, None] = '9db914ed237a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    season_phase = sa.Enum('REGULAR', 'PLAYOFFS', name='season_phase')
    season_phase.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'leagues',
        sa.Column(
            'phase',
            season_phase,
            nullable=False,
            server_default='REGULAR',
        ),
    )
    op.alter_column('leagues', 'phase', server_default=None)
    op.add_column('leagues', sa.Column('season_day', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('leagues', 'season_day', server_default=None)
    op.add_column('leagues', sa.Column('current_playoff_round', sa.String(length=30), nullable=True))
    op.add_column(
        'leagues',
        sa.Column('season_started_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.alter_column('leagues', 'season_started_at', server_default=None)
    op.add_column('matches', sa.Column('is_playoff', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('matches', 'is_playoff', server_default=None)
    op.add_column('matches', sa.Column('playoff_round', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'playoff_round')
    op.drop_column('matches', 'is_playoff')
    op.drop_column('leagues', 'season_started_at')
    op.drop_column('leagues', 'current_playoff_round')
    op.drop_column('leagues', 'season_day')
    op.drop_column('leagues', 'phase')
    # ### end Alembic commands ###
