"""add standings, scheduled fixtures, starting lineup

Revision ID: 9db914ed237a
Revises: 30c4c412bdda
Create Date: 2026-08-20 16:55:32.070582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db914ed237a'
down_revision: Union[str, None] = '30c4c412bdda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_starter', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('players', 'is_starter', server_default=None)
    op.add_column('teams', sa.Column('wins', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('teams', 'wins', server_default=None)
    op.add_column('teams', sa.Column('losses', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('teams', 'losses', server_default=None)
    op.add_column('teams', sa.Column('ties', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('teams', 'ties', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'ties')
    op.drop_column('teams', 'losses')
    op.drop_column('teams', 'wins')
    op.drop_column('players', 'is_starter')
    # ### end Alembic commands ###
