"""player espn_id unique per league instance

Revision ID: a1dfdc274c54
Revises: 51aac8e8e9d4
Create Date: 2026-08-27 08:06:37.693532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1dfdc274c54'
down_revision: Union[str, None] = '51aac8e8e9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_players_espn_id', table_name='players')
    op.create_index(op.f('ix_players_espn_id'), 'players', ['espn_id'], unique=False)
    op.create_unique_constraint('uq_players_league_espn_id', 'players', ['league_id', 'espn_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_players_league_espn_id', 'players', type_='unique')
    op.drop_index(op.f('ix_players_espn_id'), table_name='players')
    op.create_index('ix_players_espn_id', 'players', ['espn_id'], unique=True)
    # ### end Alembic commands ###
