"""add real NFL player fields

Revision ID: ac955863f955
Revises: 17f4f9ca1112
Create Date: 2026-08-20 15:15:34.050364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac955863f955'
down_revision: Union[str, None] = '17f4f9ca1112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('espn_id', sa.String(length=20), nullable=True))
    op.add_column('players', sa.Column('photo_url', sa.String(length=255), nullable=True))
    op.add_column('players', sa.Column('nfl_team', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_players_espn_id'), 'players', ['espn_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_espn_id'), table_name='players')
    op.drop_column('players', 'nfl_team')
    op.drop_column('players', 'photo_url')
    op.drop_column('players', 'espn_id')
    # ### end Alembic commands ###
