"""add team nfl_team_code

Revision ID: cfad572230c2
Revises: ac955863f955
Create Date: 2026-08-20 15:33:01.581643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfad572230c2'
down_revision: Union[str, None] = 'ac955863f955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('nfl_team_code', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_teams_nfl_team_code'), 'teams', ['nfl_team_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_nfl_team_code'), table_name='teams')
    op.drop_column('teams', 'nfl_team_code')
    # ### end Alembic commands ###
